const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;
const ERROR_INCORRECT_DATA = 400;
const STATUS_OK = 200;
const STATUS_CREATED = 201;

module.exports = {
  ERROR_NOT_FOUND, ERROR_SERVER, ERROR_INCORRECT_DATA, STATUS_OK, STATUS_CREATED,
};
